routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

//Fiscalia Controller
Route::group(['middleware'=> 'auth'], function()
{
    Route::resource('/fiscalias', 'FiscaliaController');
    Route::resource('/user', 'UserController');

});

app/Agencia.php
<?php

namespace Vehiculos;

use Illuminate\Database\Eloquent\Model;

class Agencia extends Model
{
    //
}

app/Fiscalia.php
<?php

namespace Vehiculos;

use Illuminate\Database\Eloquent\Model;

class Fiscalia extends Model
{
    protected $fillable = ['descripcion','activo'];
}

app/User.php
<?php

namespace Vehiculos;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace Vehiculos\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/FiscaliaController.php
<?php

namespace Vehiculos\Http\Controllers;

use Auth;
use Vehiculos\Fiscalia;
use Illuminate\Http\Request;

class FiscaliaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $fiscalias = Fiscalia::
      where('activo',1)
      ->orderBy('descripcion','ASC')->paginate(10);

      return view('Catalogos.fiscalias_index', compact('fiscalias'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
      return view('Catalogos.fiscalias_create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $this->validate($request,['descripcion'=> 'required','activo'=> 'required']);
      Fiscalia::create($request->all());

      return redirect()->route('fiscalias.index')->with('success', 'Registro creado correctamente');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $fiscalia = Fiscalia::find($id);
        return view('Catalogos.fiscalias_edit',compact('fiscalia'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,['descripcion'=> 'required','activo'=> 'required']);

        fiscalia::find($id)->update($request->all());
        return redirect()->route('fiscalias.index')->with('success','Registro Actualizado Exitosamente');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Fiscalia::find($id)->delete();
        return redirect()->route('fiscalias.index')->with('success','Registro Eliminado Exitosamente');
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace Vehiculos\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace Vehiculos\Http\Controllers;

use App\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $users = User::orderBy('id','DESC')->paginate(10);
      return view('Catalogos.user_index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/Catalogos/fiscalias_create.blade.php
@extends('layouts.master')
  @section('content')
  <main class="col-12 col-md-9 col-xl-8 py-md-3 pl-md-5 bd-content" role="main">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
          @if (count($errors) > 0)
            <div class="alert alert-danger">
                <strong>Error!</strong> Revise los campos obligatorios.<br><br>
                <ul>
                  @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                  @endforeach
                </ul>
            </div>
            @endif
            @if(Session::has('success'))
              <div class="alert alert-info">
                {{Session::get('success')}}
              </div>
            @endif

            <div class="panel panel-default">
                    <div class="panel-heading">
                      <h3 class="panel-title">Nueva Fiscalía</h3>
                    </div>
              <div class="panel-body">
                <div class="table-container">
                  <form method="POST" action="{{ route('fiscalias.store') }}" role="form" >
                    {{ csrf_field() }}
                        <div class="form-group">
                           <label for="descripcion">Nombre de Fiscalia</label>
                          <input type="text" name="descripcion" class="form-control" placeholder="Nombre de Fiscalia">
                        </div>
                        <div class="form-group">
                         <label for="exampleFormControlSelect1">Activo</label>
                         <select name="activo" class="form-control">
                           <option value="1">Activo</option>
                           <option value="0">Inactivo</option>
                         </select>
                        </div>
                        <div class="row">
                          <div class="col-xs-12 col-sm-12 col-md-12">
                            <input type="submit" value="Guardar" class="btn btn-success btn-block">
                            <a href="{{ route('fiscalias.index') }}" class="btn btn-info btn-block" >Atrás</a>
                          </div>
                        </div>
                  </form>
                </div>
            </div>
          </div>
      </div>
    </div>
  </section>
  @endsection

resources/views/Catalogos/fiscalias_edit.blade.php
@extends('layouts.master')

  @section('content')
  <main class="col-12 col-md-9 col-xl-8 py-md-3 pl-md-5 bd-content" role="main">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
          @if (count($errors) > 0)
            <div class="alert alert-danger">
                <strong>Error!</strong> Revise los campos obligatorios.<br><br>
                <ul>
                  @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                  @endforeach
                </ul>
            </div>
            @endif
            @if(Session::has('success'))
              <div class="alert alert-info">
                {{Session::get('success')}}
              </div>
            @endif

            <div class="panel panel-default">
                    <div class="panel-heading">
                      <h3 class="panel-title">Nueva Fiscalía</h3>
                    </div>
              <div class="panel-body">
                <div class="table-container">
                  <form method="POST" action="{{ route('fiscalias.update',$fiscalia->id) }}" role="form" >
                    {{ csrf_field() }}
                    <input name="_method" type="hidden" value="PATCH">
                      <div class="form-group">
                         <label for="descripcion">Nombre de Fiscalia</label>
                        <input type="text" name="descripcion" class="form-control input-sm" value="{{$fiscalia->descripcion}}">
                      </div>
                      <div class="form-group">
                         <label for="descripcion">Activo</label>
                         <select name="activo"  class="form-control">
                           <option value="1" @if($fiscalia->activo=="1") selected @endif>Activo </option>
                           <option value="0" @if($fiscalia->activo=="0") selected @endif>Inactivo </option>
                         </select>
                      </div>
                      <div class="row">
                        <div class="col-xs-12 col-sm-12 col-md-12">
                          <input type="submit" value="Actualizar" class="btn btn-success btn-block">
                          <a href="{{ route('fiscalias.index') }}" class="btn btn-info btn-block" >Atrás</a>
                        </div>
                      </div>
                    </form>
                  </div>
              </div>

  @endsection

resources/views/Catalogos/fiscalias_index.blade.php
@extends('layouts.master')

@section('content')
<main class="col-12 col-md-9 col-xl-8 py-md-3 pl-md-5 bd-content" role="main">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
          @if (count($errors) > 0)
            <div class="alert alert-danger">
                <strong>Error!</strong> Revise los campos obligatorios.<br><br>
                <ul>
                  @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                  @endforeach
                </ul>
            </div>
            @endif
            @if(Session::has('success'))
              <div class="alert alert-info">
                {{Session::get('success')}}
              </div>
            @endif
            <div class="panel panel-default">
                <div class="panel-heading"><h3>Fiscalias</h3></div>
                <div class="panel-body">
                  <div class="pull-left"> </div>
                  <div class="pull-right">
                    <div class="btn-group">
                      <a href="{{ route('fiscalias.create') }}" class="btn btn-info">Añadir Fiscalia </a>
                    </div>
                  </div>
                <div class="container">
                  <table id="mytable" class="table table-bordred table-striped">
                    <thead>
                      <th>Id</th>
                      <th>Nombre</th>
                      <th>Activo</th>
                      <th>Editar</th>
                      <th>Eliminar</th>
                    </thead>
                    <tbody>
                      @if($fiscalias->count())
                      @foreach($fiscalias as $fiscalia)
                        <tr>
                          <td>{{$fiscalia->id}}</td>
                          <td>{{$fiscalia->descripcion}}</td>
                          <td>{{$fiscalia->activo}}</td>
                          <td><a class="btn btn-warning" href="{{action('FiscaliaController@edit', $fiscalia->id)}}">*</a></td>
                          <td>
                              <form action="{{ action('FiscaliaController@destroy', $fiscalia->id )}}" method="post">
                                {{csrf_field()}}
                                <input name="_method" type="hidden" value="DELETE">

                                <button class="btn btn-danger btn-xs" type="submit"> - </button>
                              </form>
                          </td>
                        </tr>
                      @endforeach
                      @else
                      <tr>
                        <td colspan="8">No hay Registros</td>
                      </tr>
                      @endif
                  </tbody>
                  </table>
                </div>
              </div>
            </div>
            {{ $fiscalias->links() }}
        </div>
    </div>
</main>
@endsection

resources/views/Catalogos/user_index.blade.php
@extends('layouts.master')

@section('content')
<main class="col-12 col-md-9 col-xl-8 py-md-3 pl-md-5 bd-content" role="main">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
          @if (count($errors) > 0)
            <div class="alert alert-danger">
                <strong>Error!</strong> Revise los campos obligatorios.<br><br>
                <ul>
                  @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                  @endforeach
                </ul>
            </div>
            @endif
            @if(Session::has('success'))
              <div class="alert alert-info">
                {{Session::get('success')}}
              </div>
            @endif
            <div class="panel panel-default">
                <div class="panel-heading"><h3>Fiscalias</h3></div>
                <div class="panel-body">
                  <div class="pull-left"> </div>
                  <div class="pull-right">
                    <div class="btn-group">
                      <a href="{{ route('fiscalias.create') }}" class="btn btn-info">Añadir Fiscalia </a>
                    </div>
                  </div>
                <div class="container">
                  <table id="mytable" class="table table-bordred table-striped">
                    <thead>
                      <th>Id</th>
                      <th>Agencia</th>
                      <th>Tipo</th>
                      <th>Editar</th>
                      <th>Eliminar</th>
                    </thead>
                    <tbody>
                      @if($fiscalias->count())
                      @foreach($fiscalias as $fiscalia)
                        <tr>
                          <td>{{$fiscalia->id}}</td>
                          <td>{{$fiscalia->descripcion}}</td>
                          <td>{{$fiscalia->activo}}</td>
                          <td><a class="btn btn-warning" href="{{action('FiscaliaController@edit', $fiscalia->id)}}">*</a></td>
                          <td>
                              <form action="{{ action('FiscaliaController@destroy', $fiscalia->id )}}" method="post">
                                {{csrf_field()}}
                                <input name="_method" type="hidden" value="DELETE">

                                <button class="btn btn-danger btn-xs" type="submit"> - </button>
                              </form>
                          </td>
                        </tr>
                      @endforeach
                      @else
                      <tr>
                        <td colspan="8">No hay Registros</td>
                      </tr>
                      @endif
                  </tbody>
                  </table>
                </div>
              </div>
            </div>
            {{ $fiscalias->links() }}
        </div>
    </div>
</main>
@endsection

resources/views/home.blade.php
@extends('layouts.master')

@section('content')
<main class="col-12 col-md-9 col-xl-8 py-md-3 pl-md-5 bd-content" role="main">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif
                    
                </div>
            </div>
        </div>
    </div>
</main>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Vehiculos') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse" aria-expanded="false">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Vehiculos') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @guest
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html lang="{{app()->getLocale() }}">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- CSRF Token -->
  <meta name="csrf-token" content="{{ csrf_token() }}">

  <title>{{ config('app.name', 'Vehiculos') }}</title>

  <!-- Styles -->
  <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
<div class="container-fluid">
  <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
    <a class="navbar-brand" href="{{ url('/') }}">{{ config('app.name', 'Vehiculos') }}</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <!-- Authentication Links -->
        @guest
            <a class="nav-link" href="{{ route('login') }}">Login</a>
        @else
        <ul class="nav navbar-nav navbar-right">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{{ route('home') }}">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Catalogos
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{{ route('fiscalias.index') }}">Fiscalias</a>
              <a class="dropdown-item" href="">Agencias</a>
              <a class="dropdown-item" href="#">Usuarios</a>
              <a class="dropdown-item" href="#"></a>
            </div>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Vehiculos
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Validar</a>
              <a class="dropdown-item" href="#">Folios C5</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Asignar Masivo</a>
              <a class="dropdown-item" href="#">Asignar Individual</a>
              <a class="dropdown-item" href="#">Desasignar</a>
            </div>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Reportes
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Consulta NUC</a>
              <a class="dropdown-item" href="#">Consulta Vehiculos</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Reporte PDF</a>
              <a class="dropdown-item" href="#">Reporte Excel</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Movimientos</a>
            </div>
          </li>
          <!--<form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </ul>-->
          <!--<a class="nav-link" href="{{ route('register') }}">Register</a>-->
            <li class="dropdown" aria-labelledby="navbarDropdown">
                <a href="#" class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false" aria-haspopup="true" v-pre>
                    {{ Auth::user()->name }} <span class="caret"></span>
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a href="{{ route('logout') }}" class="dropdown-item"
                            onclick="event.preventDefault();
                                     document.getElementById('logout-form').submit();">
                            Logout
                        </a>
                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            {{ csrf_field() }}
                        </form>
                </div>
            </li>
              </ul>
        @endguest
    </div>
  </nav>
  @yield('content')
  <!-- Scripts -->
</div>
  <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>